### ISSUE TITLE
[info] - are you guys using this on production

### ISSUE THREAD

**Issue by wkhayrattee** [humanmade/batcache#14]
This is not a bug or report. I am asking additional info. 
I also understand you don't have to respond to this, but I'd appreciate the feedback.

1) are you guys using this fork on production?
2) curious as to why you have not merged [this commit](https://github.com/Automattic/batcache/commit/1c5cd87c3da8c0224b13f51f9f3362eccb1c3811) from Automattic
3) does this plugin play well for:
i) mobile version of the site (assume responsive design vs amp)
ii) WooCommerce

Cheers

**Comment by rmccue** [comment]
👋 

> are you guys using this fork on production?

Yes; we're currently in the process of a rewrite though to improve testability, so keep an eye out for that in the coming weeks.

> curious as to why you have not merged [this commit](https://github.com/Automattic/batcache/commit/1c5cd87c3da8c0224b13f51f9f3362eccb1c3811) from Automattic

We merged a different fix in https://github.com/humanmade/batcache/pull/12/ which instead just makes the Origin header part of the key.

> mobile version of the site (assume responsive design vs amp)

AMP is a different URL typically (`/amp/` suffix) so should be no issues there. If you have additional headers that need checking, you can add those to `$batcache['unique']` in your config.

> WooCommerce

WooCommerce is tricky for page caching, so you'll need to assess the situation yourself as to what's cachable and what isn't. We don't have anything specific to WooCommerce, and general advice on Automattic's version of Batcache would carry across to this fork too.
