### ISSUE TITLE
Fix Deprecation Notice warning in batcache when using PHP 8.2

### ISSUE THREAD

**Issue by wisyhambolu** [humanmade/batcache#28]
### Description 

When using PHP 8.2 on Altis v15 beta, the below warning is reported in the PHP logs

`Deprecated Creation of dynamic property batcache::$cookie is deprecated vendor/humanmade/batcache/advanced-cache.php:461`

https://github.com/humanmade/batcache/blob/master/advanced-cache.php#L461

- [ ] Fix deprecation notice

**Comment by ferschubert-hm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/batcache/28?planning-poker) with Zenhub @jerico @kovshenin @mikelittle @wisyhambolu

**Comment by jerico** [comment]
Would this be addressed by adding `var $cookie = '';` to [batcache class](https://github.com/humanmade/batcache/blob/master/advanced-cache.php#L27)?

https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by kovshenin** [comment]
> Would this be addressed by adding `var $cookie = '';`

Yes. However, the property is only used in the foreach loop to iterate over the cookie keys. After the loop it will contain the last key it saw, I don't think that's very useful. I guess the original intent was to not pollute the global namespace. I made a PR to use a different variable name and remove it after the loop.
